// /app/layout.tsx
import type { Metadata } from "next";
import "./globals.css";
import AuthProvider from "@/context/AuthProvider";


export const metadata: Metadata = {
  title: "Online Exam",
  description: "Generated by online exam",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
            <head>
      <link rel="icon" href="/favicon.svg" type="image/svg" />
      </head>
      <body>
        <AuthProvider>
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
