import type { Metadata } from "next";
import "./globals.css";
import AuthProvider from "@/context/AuthProvider";
import Navbar from "@/containers/Navabr";


export const metadata: Metadata = {
  title: "Online Exam",
  description: "Generated by online exam",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>
          <Navbar/>
        {children}
        </AuthProvider>
      </body>
    </html>
  );
}
