import type { Metadata } from "next";
import "./globals.css";
import AuthProvider from "@/context/AuthProvider";
import SideBanner from "./sideBanner/sideBanner";
import Navbar from "@/containers/Navabr";
import SocialProviders from '@/containers/AuthLayout/SocialProviders'
// import Navbar from "@/containers/Navabr";


export const metadata: Metadata = {
  title: "Online Exam",
  description: "Generated by online exam",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>
          {/* <Navbar/> */}
          
          <div className={`grid grid-cols-2 h-screen`}>
      <div className="">
      <SideBanner/>
      </div>
      <div className="">
        <Navbar/>
      {children}
      <SocialProviders/>
      </div>
    </div>
        
        </AuthProvider>
      </body>
    </html>
  );
}
